output$textRanking <- renderUI({
  list(
    h4("About"),
    HTML("A confidence curve is generated by plotting the
    evolution of an error statistic (here the MAE) when
    an increasing percentage of the errors associated
    with the largest uncertainties are removed from the
    dataset.
    <ul>
      <li> <b>Oracle</b>: an Oracle curve results from a
           perfect predictor, such as |E| = +/-uE.
           This is often an irrealistic error model,
           and no validation dataset can match the
           Oracle curve.
      <li> <b>Ideal</b>: an Ideal curve is built by taking
           the uncertainties from the dataset and
           generating ideal errors such as E~N(0,uE).
           This is more realistic than an Oracle.
           A confidence interval can be built around the
           Ideal curve by repeating the sampling of
           ideal errors. <em>Advanced parameters</em>
           enable to appreciate the effect of the ideal
           errors generative distribution and of the sampling
           size.
    </ul>
    ")
  )
})


rangesRanking <- reactiveValues(x = NULL, y = NULL)
output$plotRanking <- renderPlot({
  validate(
    need(
      !is.null(input$dataFile),
      'Please choose a datafile !'
    )
  )

  xlim = rangesRanking$x
  ylim = rangesRanking$y

  if(input$statRank == 'RMSD') {
    stat = sd
    ylab = 'RMSD / RMSD0'
  } else   if(input$statRank == 'Q95') {
    stat = ErrViewLib::q95hd
    ylab = 'Q95 / Q950'
  } else {
    stat = ErrViewLib::mue
    ylab = 'MAE / MAE0'
  }

  ErrViewLib::plotConfidence(
    E, uE,
    stat = stat,
    ylab = ylab,
    oracle = 'oracle' %in% input$choicesRank,
    ideal = 'ideal' %in% input$choicesRank,
    conf_ideal = 'idealCI' %in% input$choicesRank,
    rep_ideal = max(50,input$repIdealRank),
    dist_ideal = input$distIdealRank,
    xlim = xlim,
    ylim = ylim,
    title = paste0(
      'Confidence Curve / RCC(uE,|E|) = ',
      signif(cor(uE,abs(E),method = 'spearman'),2)
    ),
    gPars = gPars
  )
},
width = plotWidth, height = plotHeight)


observeEvent(input$Ranking_dblclick, {
  brush <- input$Ranking_brush
  if (!is.null(brush)) {
    rangesRanking$x <- c(brush$xmin, brush$xmax)
    rangesRanking$y <- c(brush$ymin, brush$ymax)
  } else {
    rangesRanking$x <- NULL
    rangesRanking$y <- NULL
  }
})

